/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_java_io_File */

#ifndef _Included_io_java_io_File
#define _Included_io_java_io_File
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_java_io_File
 * Method:    Read
 * Signature: (Lio/java/lang/Callback;[Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_io_java_io_File_Read
  (JNIEnv *, jobject, jobject, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
