/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_java_lang_Timer */

#ifndef _Included_io_java_lang_Timer
#define _Included_io_java_lang_Timer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_java_lang_Timer
 * Method:    start
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_io_java_lang_Timer_start
  (JNIEnv *, jobject);

/*
 * Class:     io_java_lang_Timer
 * Method:    stop
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_io_java_lang_Timer_stop
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
