/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class io_java_lang_System */

#ifndef _Included_io_java_lang_System
#define _Included_io_java_lang_System
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     io_java_lang_System
 * Method:    setTimeout
 * Signature: (Lio/java/lang/Callback;I[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_io_java_lang_System_setTimeout
  (JNIEnv *, jclass, jobject, jint, jobjectArray);

/*
 * Class:     io_java_lang_System
 * Method:    setRepeate
 * Signature: (Lio/java/lang/Callback;I[Ljava/lang/Object;)I
 */
JNIEXPORT jint JNICALL Java_io_java_lang_System_setRepeate
  (JNIEnv *, jclass, jobject, jint, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
